version: '3.8'
services:
  # Il nostro sito web
  webapp:
    build: .
    container_name: akinator_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # Il database MySQL
  db:
    image: mysql:8.0
    container_name: akinator_db
    environment:
      MYSQL_DATABASE: akinator_game
      MYSQL_ROOT_PASSWORD: password_segreta
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: